//
// sheet.c
//
// Copyright (C) 2007,2008 Robert William Fuller <hydrologiccycle@gmail.com>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

#include "macros.h"
#include "unix.h"
#include "cued.h" // CUED_VERSION

#define DO_NOT_WANT_PARANOIA_COMPATIBILITY
#include <cdio/cdio.h>
#include "cdio2.h"
#include "sheet.h"
#include "qsc.h"

#include <stdlib.h> // atoll


void cued_write_cuefile(
    rip_context_t *rip,
    const char *devName,
    track_t firstTrack,
    track_t lastTrack
    )
{
    PIT(char, devFileName);
    long long nmcn;
    int quoted, channels;
    track_t track;
    lsn_t firstTrackSector;

    devFileName = noextname(devName);
    if (!devFileName) {
        cdio2_abort("out of memory creating FILE command for \"%s\"", devName);
    }

    // output disc level cue info
    //

    fprintf(rip->cueFile, "REM COMMENT Generated by " CUED_PRODUCT_NAME " " CUED_VERSION "\n");

    // some drives return garbage for the MCN, so try the sub-channel data first
    if (rip->mcn[0]) {
        fprintf(rip->cueFile, "CATALOG %s\n", rip->mcn);
    } else {
        char *mcn = cdio_get_mcn(rip->cdObj);
        if (mcn) {
            if ((nmcn = atoll(mcn))) {
                if (strchr(mcn, ' ')) {

                    // Nero is buggy, to say the least
                    fprintf(rip->cueFile, "CATALOG %013lld\n", nmcn);
                } else {
                    fprintf(rip->cueFile, "CATALOG %s\n", mcn);
                }
            }
            free(mcn);
        }
    }

    cdio2_fprint_cd_text(rip->cueFile, rip->cdObj, 0, "");

    quoted = strchr(basename2(devFileName), ' ') ? 1 : 0;
    fprintf(rip->cueFile
        , "FILE %s%s.bin%s BINARY\n"
        , quoted ? "\"" : ""
        , basename2(devFileName)
        , quoted ? "\"" : ""
        );
    free(devFileName);

    firstTrackSector = cdio_get_track_lsn(rip->cdObj, 1);
    if (CDIO_INVALID_LSN == firstTrackSector) {
        cdio2_abort("failed to get first sector number for first track");
    }

    for (track = firstTrack;  track <= lastTrack;  ++track) {

        lba_t *ripLba;
        lba_t lba, useLba;
        track_flag_t flagrc;
        int preemp, copy, index;
        char msfStr[ MSF_LEN + 1 ];

        if (TRACK_FORMAT_AUDIO != cdio_get_track_format(rip->cdObj, track)) {
            cdio_warn("track %02d is not an audio track; skipping track", track);
            continue;
        }

        channels = cdio2_get_track_channels(rip->cdObj, track);

        flagrc = cdio_get_track_preemphasis(rip->cdObj, track);
        if (CDIO_TRACK_FLAG_TRUE != flagrc && CDIO_TRACK_FLAG_FALSE != flagrc) {
            cdio_warn("failed to get pre-emphasis flag for track %02d; assuming no pre-emphasis", track);
            preemp = 0;
        } else {
            preemp = (CDIO_TRACK_FLAG_TRUE == flagrc) ? 1 : 0;
        }

        flagrc = cdio_get_track_copy_permit(rip->cdObj, track);
        if (CDIO_TRACK_FLAG_TRUE != flagrc && CDIO_TRACK_FLAG_FALSE != flagrc) {
            cdio_warn("failed to get copy permitted flag for track %02d; assuming no copy permitted", track);
            copy = 0;
        } else {
            copy = (CDIO_TRACK_FLAG_TRUE == flagrc) ? 1 : 0;
        }

        // output track level cue info
        //

        fprintf(rip->cueFile, "  TRACK %02d AUDIO\n", track);
        cdio2_fprint_cd_text(rip->cueFile, rip->cdObj, track, "    ");
        if (preemp || copy || (4 == channels)) {
            fprintf(rip->cueFile, "    FLAGS%s%s%s\n", copy ? " DCP" : "", (4 == channels) ? " 4CH" : "", preemp ? " PRE" : "");
        }

        if (rip->isrc[track][0]) {
            fprintf(rip->cueFile, "    ISRC %s\n", rip->isrc[track]);
        }

        lba = cdio_get_track_lba(rip->cdObj, track);
        if (CDIO_INVALID_LBA == lba) {
            cdio2_abort("failed to get first sector number for track %02d", track);
        }

        ripLba = rip->indices[track];
        if (ripLba[1]) {
            for (index = 0;  index < CUED_MAX_INDICES;  ++index) {

                useLba = ripLba[index];
                if (!useLba) {
                    if (!index) {
                        continue;
                    } else {
                        break;
                    }
                }

                if (index <= 1 && useLba > lba) {
                    cdio_warn("index %02d from Q sub-channel for track %02d is greater than index from TOC (lba=%d > lba=%d); using TOC",
                        index, track, useLba, lba);
                    useLba = lba;
                }

                if (1 == track && !index && ripSilentPregap) {

                    // pregap for first track was silent; track 0 was deleted; use PREGAP directive in cuesheet
                    if (!qsc_lsn_to_ascii_for_cue(firstTrackSector, msfStr)) {
                        fprintf(rip->cueFile, "    PREGAP %s\n", msfStr);
                    } else {
                        cdio2_abort("failed to convert pre-gap for track %02d", track);
                    }
                } else {

                    // if pregap is silent, adjust index for the fact that pregap was not saved
                    if (ripSilentPregap) {
                        useLba -= firstTrackSector;
                    }

                    if (!qsc_lba_to_ascii_for_cue(useLba, msfStr)) {
                        fprintf(rip->cueFile, "    INDEX %02d %s\n", index, msfStr);
                    } else {
                        cdio2_abort("failed to convert index %02d for track %02d", index, track);
                    }
                }
            }
        } else {
            useLba = lba;

            if (ripSilentPregap) {
                useLba -= firstTrackSector;
                if (1 == track) {
                    if (!qsc_lsn_to_ascii_for_cue(firstTrackSector, msfStr)) {
                        fprintf(rip->cueFile, "    PREGAP %s\n", msfStr);
                    } else {
                        cdio2_abort("failed to convert pre-gap for track %02d", track);
                    }
                }
            }

            if (!qsc_lba_to_ascii_for_cue(useLba, msfStr)) {
                fprintf(rip->cueFile, "    INDEX %02d %s\n", 1, msfStr);
            } else {
                cdio2_abort("failed to convert index for track %02d", track);
            }
        }
    }

    if (rip->cueFile != stdout) {
        fclose(rip->cueFile);
    }
}
